# Generated by Django 5.2.17 on 2026-09-23 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text="Identique à la date de début pour une activité d'un seul jour.", verbose_name='Date de fin')),
                ('visibilite', models.CharField(choices=[('public', 'Publique (visible par tous les visiteurs)'), ('prive', 'Privée (visible uniquement par les personnes connectées)')], default='public', max_length=10, verbose_name='Visibilité')),
                ('couleur', models.CharField(blank=True, help_text='Code couleur hexadécimal (ex : #2e7d32). Laisser vide pour une attribution automatique selon la visibilité.', max_length=7, verbose_name="Couleur d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone / GSM')),
                ('date_debut', models.DateField(verbose_name='Date de début souhaitée')),
                ('date_fin', models.DateField(help_text="Identique à la date de début pour une réservation d'un seul jour.", verbose_name='Date de fin souhaitée')),
                ('message', models.TextField(blank=True, verbose_name='Précisions sur la demande')),
                ('statut', models.CharField(choices=[('attente', 'En attente de traitement'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='attente', max_length=10, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Demande reçue le')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Traitée le')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Demande de réservation de salle',
                'verbose_name_plural': 'Demandes de réservation de salle',
                'ordering': ['-date_demande'],
            },
        ),
    ]
