# Generated by Django 5.2.17 on 2026-09-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegue_prenom', models.CharField(max_length=100, verbose_name="Prénom du délégué de l'ASBL")),
                ('delegue_nom', models.CharField(max_length=100, verbose_name="Nom du délégué de l'ASBL")),
                ('local_salle', models.BooleanField(default=True, verbose_name='Une salle des fêtes et une scène')),
                ('local_cafe', models.BooleanField(default=False, verbose_name='Local dénommé café')),
                ('local_cuisine', models.BooleanField(default=False, verbose_name='Cuisine équipée')),
                ('local_toilettes', models.BooleanField(default=False, verbose_name='Un ensemble sanitaire (toilettes)')),
                ('montant_location', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant de la location (€)')),
                ('montant_caution', models.DecimalField(decimal_places=2, default=150, max_digits=8, verbose_name='Montant de la caution (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='contrats_location/', verbose_name='Fichier PDF du contrat')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='calendrier.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'verbose_name_plural': 'Contrats de location',
            },
        ),
    ]
