# Generated by Django 5.2.17 on 2026-09-27 09:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLibre',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('titre_affiche', models.CharField(blank=True, help_text='Facultatif : si laissé vide, le titre de la page (ci-dessus) est utilisé.', max_length=255, verbose_name='Titre affiché')),
                ('sous_titre', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('titre_galerie', models.CharField(blank=True, help_text="Facultatif : laissez vide pour n'afficher aucune galerie.", max_length=255, verbose_name='Titre de la galerie de miniatures')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Page libre',
                'verbose_name_plural': 'Pages libres',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PageLibreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende (facultative)')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='page_libre.pagelibre')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageLibreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type_section', models.CharField(choices=[('normal', 'Défilement normal (image + texte)'), ('colonnes', 'Colonnes (1 à 3)')], default='normal', help_text="Détermine quels champs ci-dessous sont utilisés à l'affichage.", max_length=10, verbose_name='Type de section')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titre')),
                ('text', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('image_position', models.CharField(choices=[('left', 'Image à gauche'), ('right', 'Image à droite'), ('full', 'Image en pleine largeur (fond)')], default='left', max_length=10, verbose_name="Position de l'image")),
                ('titre_colonnes', models.CharField(blank=True, help_text='Facultatif : affiché au-dessus des colonnes.', max_length=255, verbose_name='Titre de la section')),
                ('nombre_colonnes', models.PositiveSmallIntegerField(choices=[(1, '1 colonne'), (2, '2 colonnes'), (3, '3 colonnes')], default=2, verbose_name='Nombre de colonnes')),
                ('colonne_1_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_1_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('colonne_2_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_2_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('colonne_3_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_3_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('liens', wagtail.fields.StreamField([('lien', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du lien', 'max_length': 50}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Adresse du lien'}), 2: ('wagtail.blocks.StructBlock', [[('texte', 0), ('url', 1)]], {})}, help_text='Ajoutez autant de liens que voulu (au moins deux si besoin), pour les deux types de section.', verbose_name='Liens')),
                ('colonne_1_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('colonne_2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('colonne_3_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='page_libre.pagelibre')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
