# Generated by Django 6.0.3 on 2026-03-28 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la représentation')),
                ('date', models.DateField(verbose_name='Date')),
                ('prix_adulte', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix adulte (€)')),
                ('prix_enfant', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix enfant (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Représentation',
                'verbose_name_plural': 'Représentations',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PlanSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_rangees', models.PositiveIntegerField(verbose_name='Nombre de rangées')),
                ('configuration', models.JSONField(verbose_name='Configuration des rangées (JSON)')),
                ('nb_total_places', models.PositiveIntegerField(verbose_name='Nombre total de places')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('representation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_salle', to='theatre.representation', verbose_name='Représentation')),
            ],
            options={
                'verbose_name': 'Plan de salle',
                'verbose_name_plural': 'Plans de salle',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nb_adultes', models.PositiveIntegerField(default=0, verbose_name="Nombre d'adultes")),
                ('nb_enfants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('preference_rangee', models.CharField(choices=[('avant', 'Avant'), ('centre', 'Centre'), ('arriere', 'Arrière')], default='centre', max_length=10, verbose_name='Préférence rangée')),
                ('preference_cote', models.CharField(choices=[('gauche', 'Gauche'), ('milieu', 'Milieu'), ('droite', 'Droite')], default='milieu', max_length=10, verbose_name='Préférence côté')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix total (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='theatre.representation', verbose_name='Représentation')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceReservee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.PositiveIntegerField(verbose_name='Numéro de place')),
                ('rangee', models.PositiveIntegerField(verbose_name='Rangée')),
                ('colonne', models.PositiveIntegerField(verbose_name='Colonne')),
                ('plan_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='theatre.plansalle', verbose_name='Plan de salle')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_attribuees', to='theatre.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Place réservée',
                'verbose_name_plural': 'Places réservées',
                'ordering': ['numero_place'],
                'unique_together': {('plan_salle', 'numero_place')},
            },
        ),
    ]
