# Generated by Django 6.0.3 on 2026-03-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='preference_cote',
            field=models.CharField(blank=True, choices=[('', 'Sans préférence'), ('gauche', 'Gauche'), ('milieu', 'Milieu'), ('droite', 'Droite')], default='', max_length=10, verbose_name='Préférence côté'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='preference_rangee',
            field=models.CharField(blank=True, choices=[('', 'Sans préférence'), ('avant', 'Avant'), ('centre', 'Centre'), ('arriere', 'Arrière')], default='', max_length=10, verbose_name='Préférence rangée'),
        ),
    ]
