# Generated by Django 6.0.3 on 2026-03-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_alter_reservation_preference_cote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rangee_preferee',
            field=models.CharField(blank=True, choices=[('', 'Sans préférence'), ('1', 'Rangée 1'), ('2', 'Rangée 2'), ('3', 'Rangée 3'), ('4', 'Rangée 4'), ('5', 'Rangée 5'), ('6', 'Rangée 6')], default='', max_length=1, verbose_name='Rangée souhaitée (1-6)'),
        ),
    ]
