# Generated by Django 6.0.3 on 2026-03-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_reservation_rangee_preferee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annulé')], default='valide', max_length=10, verbose_name='Statut')),
                ('imprime_le', models.DateTimeField(auto_now_add=True, verbose_name='Imprimé le')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire (€)')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='theatre.placereservee', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['place__numero_place'],
            },
        ),
    ]
