# Generated by Django 6.0.3 on 2026-03-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.PositiveIntegerField(verbose_name='Numéro de place')),
                ('rangee', models.PositiveIntegerField(verbose_name='Rangée')),
                ('colonne', models.PositiveIntegerField(verbose_name='Colonne')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('vendue', 'Vendue (vente flash)')], default='libre', max_length=20)),
                ('plan_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_libres', to='theatre.plansalle', verbose_name='Plan de salle')),
            ],
            options={
                'verbose_name': 'Place libre',
                'verbose_name_plural': 'Places libres',
                'ordering': ['numero_place'],
                'unique_together': {('plan_salle', 'numero_place')},
            },
        ),
        migrations.CreateModel(
            name='VenteFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('tarif', models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant')], default='adulte', max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vendu_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annulé')], default='valide', max_length=10)),
                ('annule_le', models.DateTimeField(blank=True, null=True)),
                ('place_libre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente_flash', to='theatre.placelibre', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Vente flash',
                'verbose_name_plural': 'Ventes flash',
            },
        ),
        migrations.CreateModel(
            name='ZoneTampon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_liberes', models.JSONField(default=list, verbose_name='IDs des PlaceReservee libérées')),
                ('mis_en_tampon_le', models.DateTimeField(auto_now_add=True)),
                ('plan_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_tampon', to='theatre.plansalle', verbose_name='Plan de salle')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_tampon', to='theatre.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Zone tampon',
                'verbose_name_plural': 'Zones tampon',
            },
        ),
    ]
