# Generated by Django 5.2.17 on 2026-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_placelibre_venteflash_zonetampon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('acces_application', "Peut accéder à l'application Théâtre")],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
