# Generated by Django 5.2.17 on 2026-09-27 09:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsindexpage_canonical_url_newsindexpage_og_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 5), ('callout', 8), ('useful_link', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.TextBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex : nom de l'auteur, source…", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Choisissez une page du site (prioritaire sur l'URL ci-dessous).", 'label': 'Page du site', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': "Utilisée seulement si aucune page n'est choisie ci-dessus.", 'label': 'Ou URL externe', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('page', 10), ('url', 11)]], {})}),
        ),
    ]
