# Generated by Django 5.2.17 on 2026-09-23 11:59

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='Bienvenue à La Concorde', help_text="Grand titre affiché sur le bandeau d'ouverture.", max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_cta_text', models.CharField(blank=True, default='Découvrir nos activités', max_length=50)),
                ('hero_cta_link', models.URLField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text="Court texte de présentation de l'ASBL.")),
                ('afficher_section_actualite', models.BooleanField(default=True, help_text="N'apparaît sur la page d'accueil que si une actualité a été publiée au cours des 30 derniers jours.", verbose_name="Afficher la section 'Dernière actualité'")),
                ('afficher_section_calendrier', models.BooleanField(default=True, help_text="N'apparaît sur la page d'accueil que s'il existe au moins une activité à venir dans le calendrier.", verbose_name="Afficher la section 'Prochaines activités'")),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image ou photo de fond du bandeau d'ouverture (effet de fondu à l'arrivée sur le site).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image_fond_calendrier', models.ForeignKey(blank=True, help_text='Idéalement une image évoquant un calendrier/agenda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image de fond de la section 'Prochaines activités'")),
            ],
            options={
                'verbose_name': "Page d'accueil",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageColumnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre_section', models.CharField(blank=True, help_text='Facultatif : affiché au-dessus des colonnes.', max_length=255, verbose_name='Titre de la section')),
                ('nombre_colonnes', models.PositiveSmallIntegerField(choices=[(1, '1 colonne'), (2, '2 colonnes'), (3, '3 colonnes')], default=2, verbose_name='Nombre de colonnes')),
                ('colonne_1_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_1_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('colonne_2_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_2_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('colonne_3_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('colonne_3_texte', wagtail.fields.RichTextField(blank=True, verbose_name='Texte')),
                ('colonne_1_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('colonne_2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('colonne_3_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_colonnes', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Section en colonnes',
            },
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('image_position', models.CharField(choices=[('left', 'Image à gauche'), ('right', 'Image à droite'), ('full', 'Image en pleine largeur (fond)')], default='left', max_length=10)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, help_text='URL externe ou chemin interne, ex : /calendrier/', max_length=500)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
