# Generated by Django 5.2.17 on 2026-09-26 13:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_1_texte',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_1_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_2_texte',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_2_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_3_texte',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='colonne_3_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='nombre_colonnes',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 colonne'), (2, '2 colonnes'), (3, '3 colonnes')], default=2, verbose_name='Nombre de colonnes'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='titre_colonnes',
            field=models.CharField(blank=True, help_text='Facultatif : affiché au-dessus des colonnes.', max_length=255, verbose_name='Titre de la section'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='type_section',
            field=models.CharField(choices=[('normal', 'Défilement normal (image + texte)'), ('colonnes', 'Colonnes (1 à 3)')], default='normal', help_text="Détermine quels champs ci-dessous sont utilisés à l'affichage.", max_length=10, verbose_name='Type de section'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='image_position',
            field=models.CharField(choices=[('left', 'Image à gauche'), ('right', 'Image à droite'), ('full', 'Image en pleine largeur (fond)')], default='left', max_length=10, verbose_name="Position de l'image"),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='link_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Texte du lien'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL externe ou chemin interne, ex : /calendrier/', max_length=500, verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titre'),
        ),
        migrations.DeleteModel(
            name='HomePageColumnSection',
        ),
    ]
