# Generated by Django 5.2.17 on 2026-09-26 14:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagesection_colonne_1_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='homepagesection',
            name='link_url',
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='liens',
            field=wagtail.fields.StreamField([('lien', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du lien', 'max_length': 50}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Adresse du lien'}), 2: ('wagtail.blocks.StructBlock', [[('texte', 0), ('url', 1)]], {})}, help_text='Ajoutez autant de liens que voulu (au moins deux si besoin), pour les deux types de section.', verbose_name='Liens'),
        ),
    ]
