# Generated by Django 5.2.17 on 2026-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text="URL d'intégration Google Maps (menu Partager > Intégrer une carte)."),
        ),
    ]
