# Generated by Django 5.2.17 on 2026-09-26 14:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='socialsettings',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='socialsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.CreateModel(
            name='ReseauSocialLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('reseau', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('autre', 'Autre')], default='facebook', max_length=20, verbose_name='Réseau social')),
                ('libelle', models.CharField(blank=True, help_text="Ex : 'Page principale', 'Groupe des bénévoles'. Utile surtout si plusieurs liens sont ajoutés pour le même réseau.", max_length=100, verbose_name='Libellé (facultatif)')),
                ('url', models.URLField(verbose_name='Adresse du lien')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_reseaux_sociaux', to='navigation.socialsettings')),
            ],
            options={
                'verbose_name': 'Lien vers un réseau social',
                'verbose_name_plural': 'Liens vers les réseaux sociaux',
            },
        ),
    ]
