# Generated by Django 5.2.17 on 2026-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_remove_socialsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='ouvrir_nouvel_onglet',
            field=models.BooleanField(default=False, verbose_name='Ouvrir dans un nouvel onglet'),
        ),
    ]
